// localStorage polyfill for SSR - MUST BE FIRST
if (typeof window === 'undefined' && typeof global !== 'undefined') {
  const mockStorage = {
    getItem: () => null,
    setItem: () => {},
    removeItem: () => {},
    clear: () => {},
    key: () => null,
    length: 0,
  };
  
  Object.defineProperty(global, 'localStorage', {
    value: mockStorage,
    writable: false,
    configurable: false,
  });
  
  Object.defineProperty(global, 'sessionStorage', {
    value: mockStorage,
    writable: false,
    configurable: false,
  });
  
  // Also polyfill for globalThis
  if (typeof globalThis !== 'undefined') {
    Object.defineProperty(globalThis, 'localStorage', {
      value: mockStorage,
      writable: false,
      configurable: false,
    });
    
    Object.defineProperty(globalThis, 'sessionStorage', {
      value: mockStorage,
      writable: false,
      configurable: false,
    });
  }
}

import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        {children}
      </body>
    </html>
  );
}